---
label: Product
hide_body: false
display_field: name
fields:
- name: data_item_id
  type: text
  config:
    required: false
  label: id
- name: data_item_name
  type: text
  config:
    required: false
  label: name
  description: Product name
- name: data_item_price
  type: number
  label: Price
  description: Product price
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: data_item_description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
  description: Product description
- name: data_item_image
  type: file
  config:
    maxSize: 250
  label: Image
  description: Product image
- name: data_item_product_url
  type: text
  config:
    required: false
  label: Product_url
- name: data_item_file_guid
  type: text
  config:
    required: false
  label: File guid
pages:
- content/products/product1.md
- content/products/product2.md
